apiVersion: v1
kind: Service
metadata:
  name: janusgraph
  namespace: graph
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    app: janusgraph
  ports:
    - port: 8182
      targetPort: 8182
