apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: janusgraph-scylla
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_GITHUB_USERNAME/janusgraph-scylladb-gitops.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: graph
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
